---

- name: 'add new login classes'
  blockinfile:
    dest: '/etc/login.conf'
    block: |
      {{ item.name }}:\
      {% for cap in item.capabilities %}
          :{{ cap.name }}{% if cap.value is defined %}={{ cap.value }}{% endif %}:{% if not loop.last %}\{% endif %}

      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ openbsd_login_classes }}"
  register: __openbsd_login_class_result

- name: 'regenerate login.conf.db if needed'  # noqa 503
  shell: |
    cap_mkdb /etc/login.conf
  changed_when: False
  when: >
    openbsd_login_class_capdb | bool
    and __openbsd_login_class_result.changed

- name: 'restart service if needed'  # noqa 503
  service:
    name: "{{ item }}"
    state: 'restarted'
  loop: "{{ __openbsd_login_class_result.results | json_query('[?changed].item[].services[]') | list }}"
