---

- name: add a new login class
  blockinfile:
    dest: /etc/login.conf
    block: |
      {{ OpenBSD_login_class.name }}:\
      {% for cap in OpenBSD_login_class.capabilities %}
        :{{ cap.name }}{% if cap.value is defined %}={{ cap.value }}{% endif %}:{% if not loop.last %}/{% endif %}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ OpenBSD_login_class.name }}"
    state: "{{ OpenBSD_login_class.state | default('present') }}"
  register: __OpenBSD_login_class_result

- name: regenerate login.conf.db if needed
  shell: >
    [ -f /etc/login.conf.db ] && cap_mkdb /etc/login.conf
  changed_when: False
  when: __OpenBSD_login_class_result.changed

- name: restart service if needed
  service:
    name: "{{ OpenBSD_login_class.service.name }}"
    state: restarted
  when: >
    __OpenBSD_login_class_result.changed
    and OpenBSD_login_class.service is defined
    and OpenBSD_login_class.service.restart
