---

- hosts: all
  name: 'Converge'
  become: True

  tasks:
    - import_role:
        name: 'ansible-role-openbsd_login_class'
      vars:
        openbsd_login_classes:
          - name: 'molecule'

            services:
              - 'ntpd'

            capabilities:
              - name: 'openfiles'
                value: '666'

              - name: 'tc'
                value: 'daemon'

    - name: 'create a user'
      user:
        name: 'molecule'
        login_class: 'molecule'
